/* ============================================================
 * surah_meta.c - Static Surah metadata
 * Owned by: Backend Engineer
 *
 * Responsibilities:
 *   - Hardcoded array of all 114 Surahs: name, meaning,
 *     revelation type (Meccan/Medinan), ayah count, and a
 *     short context blurb for the Surah overview card.
 *   - This data never changes, so no network call is needed.
 *
 * Field values mirror the Phase-2 cached AlQuran.cloud data
 * (data/quran.json) so getSurahMeta matches the loaded ayahs.
 * ============================================================ */

#include "quran.h"

static const Surah SURAH_META[TOTAL_SURAHS] = {
  {1, "Al-Faatiha", "سُورَةُ ٱلْفَاتِحَةِ", "The Opening", "Meccan", 7, "The opening prayer of the Quran, recited in every unit of Salah. It covers praise of Allah, His mercy, and the request for guidance on the straight path."},
  {2, "Al-Baqara", "سُورَةُ البَقَرَةِ", "The Cow", "Medinan", 286, "The longest Surah, revealed over several years in Madinah. It covers the story of Adam, the Children of Israel, laws of fasting, Hajj, marriage, and contains the Throne Verse, Ayat al-Kursi."},
  {3, "Aal-i-Imraan", "سُورَةُ آلِ عِمۡرَانَ", "The Family of Imraan", "Medinan", 200, "Named after the family of Imraan, father of Maryam. It discusses the birth of Jesus, the unity of Allah, and lessons for the believers from the Battle of Uhud."},
  {4, "An-Nisaa", "سُورَةُ النِّسَاءِ", "The Women", "Medinan", 176, "Deals with the rights and responsibilities of women, family law, and inheritance shares. It also lays down rules for orphans, marriage, and justice in disputes."},
  {5, "Al-Maaida", "سُورَةُ المَائـِدَةِ", "The Table", "Medinan", 120, "Covers lawful food, the rituals of Hajj, oaths, and the penalty for transgression. It includes the final sermon of the Prophet and the verse perfecting the religion."},
  {6, "Al-An'aam", "سُورَةُ الأَنۡعَامِ", "The Cattle", "Meccan", 165, "A Meccan Surah that stresses Tawhid, the oneness of Allah, and the rejection of polytheism. It recounts the arguments of Prophet Ibrahim against idol worship and the fate of earlier nations."},
  {7, "Al-A'raaf", "سُورَةُ الأَعۡرَافِ", "The Heights", "Meccan", 206, "Tells the story of Adam and Iblees and of the people of the Heights between Paradise and Hell. It also relates the trials of the Prophets Nuh, Hud, Salih, Lut, and Musa with their nations."},
  {8, "Al-Anfaal", "سُورَةُ الأَنفَالِ", "The Spoils of War", "Medinan", 75, "Revealed after the Battle of Badr, it covers the distribution of war spoils and the ethics of conflict. It emphasizes trust in Allah and unity among the believers."},
  {9, "At-Tawba", "سُورَةُ التَّوۡبَةِ", "The Repentance", "Medinan", 129, "The only Surah without the Bismillah, dealing with treaties and the final break with the idolaters. It also recounts the Battle of Tabuk and the lesson of the three who stayed behind."},
  {10, "Yunus", "سُورَةُ يُونُسَ", "Jonas", "Meccan", 109, "Named after Prophet Yunus, who was swallowed by the great fish. It affirms the Quran as revelation and gives glad tidings and warnings to the people."},
  {11, "Hud", "سُورَةُ هُودٍ", "Hud", "Meccan", 123, "Named after Prophet Hud, sent to the people of Aad. It repeatedly warns that no nation is saved by wealth or power, only by faith in Allah."},
  {12, "Yusuf", "سُورَةُ يُوسُفَ", "Joseph", "Meccan", 111, "The detailed story of Prophet Yusuf, the jealousy of his brothers, his trials in Egypt, and his eventual rise to power. Considered the best of stories, it is a lesson in patience and trust in Allah."},
  {13, "Ar-Ra'd", "سُورَةُ الرَّعۡدِ", "The Thunder", "Medinan", 43, "The thunder glorifies Allah as a sign of His power. It discusses revelation and the resurrection, and that conditions change only when peoples change what is in themselves."},
  {14, "Ibrahim", "سُورَةُ إِبۡرَاهِيمَ", "Abraham", "Meccan", 52, "Named after Prophet Ibrahim, the friend of Allah. It recalls his prayer for Makkah and its people and the gratitude owed to Allah for His blessings."},
  {15, "Al-Hijr", "سُورَةُ الحِجۡرِ", "The Rock", "Meccan", 99, "Takes its name from the rocky tract where the people of Thamud lived. It comforts the Prophet with the fate of previous nations who rejected their messengers."},
  {16, "An-Nahl", "سُورَةُ النَّحۡلِ", "The Bee", "Meccan", 128, "The bee is cited as a sign of the design and provision of Allah. The Surah stresses gratitude for creation, food, and the guidance of the Quran."},
  {17, "Al-Israa", "سُورَةُ الإِسۡرَاءِ", "The Night Journey", "Meccan", 111, "Opens with the night journey of the Prophet from Makkah to Jerusalem. It contains the wise counsel against idolatry, killing, and squandering, and honors the parents."},
  {18, "Al-Kahf", "سُورَةُ الكَهۡفِ", "The Cave", "Meccan", 110, "Relates four stories, the people of the Cave, the owner of two gardens, Musa and Khidr, and Dhul-Qarnayn. It is recommended to recite on Fridays as a protection from the trial of the Dajjal."},
  {19, "Maryam", "سُورَةُ مَرۡيَمَ", "Mary", "Meccan", 98, "Named after Maryam, the mother of Prophet Isa. It tells of the miraculous birth of Jesus and the stories of Zakariyya, Yahya, and other prophets."},
  {20, "Taa-Haa", "سُورَةُ طه", "Taa-Haa", "Meccan", 135, "Named after the two mysterious letters with which it opens. It recounts the mission of Musa and Harun to Pharaoh and the lesson of the golden calf."},
  {21, "Al-Anbiyaa", "سُورَةُ الأَنبِيَاءِ", "The Prophets", "Meccan", 112, "Reviews the struggles of many prophets, including Ibrahim, Musa, and Yunus. It affirms that the messengers were human beings chosen by Allah."},
  {22, "Al-Hajj", "سُورَةُ الحَجِّ", "The Pilgrimage", "Medinan", 78, "Discusses the rites and purpose of the pilgrimage to Makkah. It mixes Meccan themes of the resurrection with Medinan rulings on struggle and worship."},
  {23, "Al-Muminoon", "سُورَةُ المُؤۡمِنُونَ", "The Believers", "Meccan", 118, "Lists the qualities of the successful believers, such as humility in prayer and guarding the chastity. It contrasts their fate with that of the disbelievers."},
  {24, "An-Noor", "سُورَةُ النُّورِ", "The Light", "Medinan", 64, "Contains the ruling on slander and the requirement of four witnesses. The famous light verse describes the guidance of Allah as a light within the believers."},
  {25, "Al-Furqaan", "سُورَةُ الفُرۡقَانِ", "The Criterion", "Meccan", 77, "Al-Furqaan is another name of the Quran, the criterion between truth and falsehood. It describes the servants of the Most Merciful and their noble qualities."},
  {26, "Ash-Shu'araa", "سُورَةُ الشُّعَرَاءِ", "The Poets", "Meccan", 227, "Mentions the poets who wander in every valley. It recounts the stories of Musa, Ibrahim, Nuh, Hud, Salih, Lut, and Shuayb warning their peoples."},
  {27, "An-Naml", "سُورَةُ النَّمۡلِ", "The Ant", "Meccan", 93, "Named after the ant that spoke to Prophet Sulayman. It tells the story of Sulayman and the Queen of Sheba and the wisdom of the hoopoe bird."},
  {28, "Al-Qasas", "سُورَةُ القَصَصِ", "The Stories", "Meccan", 88, "Means the stories, focusing on the life of Prophet Musa from his birth to his mission. It includes the story of Qarun and his downfall due to arrogance."},
  {29, "Al-Ankaboot", "سُورَةُ العَنكَبُوتِ", "The Spider", "Meccan", 69, "The spider is cited as the weakest of all homes, likened to the weak shelters of those who take protectors besides Allah. It stresses that faith is tested through hardship."},
  {30, "Ar-Room", "سُورَةُ الرُّومِ", "The Romans", "Meccan", 60, "Predicts the defeat of the Romans and their later victory within a few years. It urges reflection on the creation as proof of the resurrection."},
  {31, "Luqman", "سُورَةُ لُقۡمَانَ", "Luqman", "Meccan", 34, "Named after the wise man Luqman who advised his son. His counsel covers gratitude, kindness to parents, and humility in walking and speaking."},
  {32, "As-Sajda", "سُورَةُ السَّجۡدَةِ", "The Prostration", "Meccan", 30, "Describes the creation of humanity and the prostration of the angels before Adam. It warns of the Day of Judgment and describes the believers who prostrate to Allah."},
  {33, "Al-Ahzaab", "سُورَةُ الأَحۡزَابِ", "The Clans", "Medinan", 73, "Revealed during the battle of the Trench, when the allies besieged Madinah. It addresses the family life of the Prophet and the standards of modesty for the believers."},
  {34, "Saba", "سُورَةُ سَبَإٍ", "Sheba", "Meccan", 54, "Named after the people of Saba who were blessed with a fertile land. Their ingratitude brought the flood of the dam, a lesson on the consequences of thanklessness."},
  {35, "Faatir", "سُورَةُ فَاطِرٍ", "The Originator", "Meccan", 45, "The Originator of the heavens and the earth. It emphasizes that only the creation of Allah is worthy of worship and that no soul bears the burden of another."},
  {36, "Yaseen", "سُورَةُ يسٓ", "Yaseen", "Meccan", 83, "Called the heart of the Quran. It affirms the revelation, warns of the fate of the town that rejected its messengers, and stresses the power of Allah to resurrect."},
  {37, "As-Saaffaat", "سُورَةُ الصَّافَّاتِ", "Those drawn up in Ranks", "Meccan", 182, "Opens with the angels standing in ranks. It relates the story of Ibrahim and the great sacrifice and confirms the protection of the messengers."},
  {38, "Saad", "سُورَةُ صٓ", "The letter Saad", "Meccan", 88, "Opens with the letter Saad. It defends the Quran against mockery and recounts the trials of Dawud, Sulayman, Ayyub, and Adam."},
  {39, "Az-Zumar", "سُورَةُ الزُّمَرِ", "The Groups", "Meccan", 75, "The troops or groups, describing how believers and disbelievers will be driven in groups to their final destination. It urges sincere devotion to Allah alone."},
  {40, "Ghafir", "سُورَةُ غَافِرٍ", "The Forgiver", "Meccan", 85, "The Forgiver of sins and the Acceptor of repentance. It includes the story of the believing man from the family of Pharaoh who defended Musa."},
  {41, "Fussilat", "سُورَةُ فُصِّلَتۡ", "Explained in detail", "Meccan", 54, "Means explained in detail, referring to the clear verses of the Quran. It describes the creation of the heavens and earth and the witnesses against the disbelievers on Judgment Day."},
  {42, "Ash-Shura", "سُورَةُ الشُّورَىٰ", "Consultation", "Meccan", 53, "The consultation, encouraging the believers to settle their affairs by mutual consultation. It stresses that the messengers were sent as warners and bearers of glad tidings."},
  {43, "Az-Zukhruf", "سُورَةُ الزُّخۡرُفِ", "Ornaments of gold", "Meccan", 89, "Mentions the ornaments of gold with which worldly life is decorated. It rejects the worship of idols and the claim that angels are daughters of Allah."},
  {44, "Ad-Dukhaan", "سُورَةُ الدُّخَانِ", "The Smoke", "Meccan", 59, "The smoke, a sign of the coming punishment. It was revealed at a time of severe famine in Makkah and points to the great Day of smoke."},
  {45, "Al-Jaathiya", "سُورَةُ الجَاثِيَةِ", "Crouching", "Meccan", 37, "The crouching, when every community will kneel before Allah. It warns the deniers of the verses of Allah and describes their regret."},
  {46, "Al-Ahqaf", "سُورَةُ الأَحۡقَافِ", "The Dunes", "Meccan", 35, "Named after the sand dunes where the people of Aad lived. It recounts the call of Prophet Hud and the fate of those who rejected him."},
  {47, "Muhammad", "سُورَةُ مُحَمَّدٍ", "Muhammad", "Medinan", 38, "Named after the Prophet, it addresses the believers in Madinah. It urges fighting in the way of Allah and describes the state of the hypocrites."},
  {48, "Al-Fath", "سُورَةُ الفَتۡحِ", "The Victory", "Medinan", 29, "The victory, referring to the treaty of Hudaybiyyah which was a great opening. It reassures the believers of the help of Allah and promises the conquest of Makkah."},
  {49, "Al-Hujuraat", "سُورَةُ الحُجُرَاتِ", "The Inner Apartments", "Medinan", 18, "The rooms of the Prophet. It teaches proper manners toward the Prophet and the believers and stresses that nobility is by piety, not lineage."},
  {50, "Qaaf", "سُورَةُ قٓ", "The letter Qaaf", "Meccan", 45, "Opens with the letter Qaf. It affirms the resurrection and the recording of deeds and recalls the fate of earlier disbelieving nations."},
  {51, "Adh-Dhaariyat", "سُورَةُ الذَّارِيَاتِ", "The Winnowing Winds", "Meccan", 60, "The winnowing winds that scatter, one of the oaths of the Surah. It warns of the coming judgment and recounts the honor given to the guests of Ibrahim."},
  {52, "At-Tur", "سُورَةُ الطُّورِ", "The Mount", "Meccan", 49, "The mount, where Musa received the revelation. It swears by the mountain and the sacred book and describes the gardens promised to the righteous."},
  {53, "An-Najm", "سُورَةُ النَّجۡمِ", "The Star", "Meccan", 62, "The star, and the first Surah revealed entirely at once. It describes the night journey of the Prophet and rejects the worship of idols."},
  {54, "Al-Qamar", "سُورَةُ القَمَرِ", "The Moon", "Meccan", 55, "The moon, which was split as a sign for the disbelievers. It warns of the fate of previous nations who rejected their messengers."},
  {55, "Ar-Rahmaan", "سُورَةُ الرَّحۡمَٰن", "The Beneficent", "Medinan", 78, "The Most Merciful, repeating the question which of the favors of your Lord will you deny. It lists the blessings of Allah in this world and the next."},
  {56, "Al-Waaqia", "سُورَةُ الوَاقِعَةِ", "The Inevitable", "Meccan", 96, "The inevitable event, the Day of Judgment. It divides people into the foremost, the people of the right hand, and the people of the left hand."},
  {57, "Al-Hadid", "سُورَةُ الحَدِيدِ", "The Iron", "Medinan", 29, "The iron, cited as a sign of the power of Allah sent down with great force. It urges spending in charity and fearing Allah."},
  {58, "Al-Mujaadila", "سُورَةُ المُجَادلَةِ", "The Pleading Woman", "Medinan", 22, "The woman who pleaded with the Prophet about her husband. It sets the ruling on zihar and emphasizes the fear of Allah in disputes."},
  {59, "Al-Hashr", "سُورَةُ الحَشۡرِ", "The Exile", "Medinan", 24, "The exile, referring to the expulsion of the Jewish tribe of Banu Nadir from Madinah. It praises the emigrants and helpers and describes the attributes of Allah."},
  {60, "Al-Mumtahana", "سُورَةُ المُمۡتَحنَةِ", "She that is to be examined", "Medinan", 13, "The woman who is examined. It lays down the rules for testing emigrant women and for maintaining ties with non-believing relatives in peace."},
  {61, "As-Saff", "سُورَةُ الصَّفِّ", "The Ranks", "Medinan", 14, "The ranks, in which Allah loves those who fight in His cause in rows. It recalls the promise of Jesus of a messenger to come after him, Ahmad."},
  {62, "Al-Jumu'a", "سُورَةُ الجُمُعَةِ", "Friday", "Medinan", 11, "Friday, the day of the congregational prayer. It rebukes those who leave the prayer for trade and stresses the preference of the remembrance of Allah over business."},
  {63, "Al-Munaafiqoon", "سُورَةُ المُنَافِقُونَ", "The Hypocrites", "Medinan", 11, "The hypocrites, who claim faith while concealing disbelief. It exposes their excuses and warns the Prophet against their deception."},
  {64, "At-Taghaabun", "سُورَةُ التَّغَابُنِ", "Mutual Disillusion", "Medinan", 18, "Mutual disillusion, when the losers and winners will be shown on Judgment Day. It urges obedience to Allah and His messenger and spending in charity."},
  {65, "At-Talaaq", "سُورَةُ الطَّلَاقِ", "Divorce", "Medinan", 12, "The divorce, giving detailed rules for the waiting period and reconciliation. It promises provision for those who fear Allah."},
  {66, "At-Tahrim", "سُورَةُ التَّحۡرِيمِ", "The Prohibition", "Medinan", 12, "The prohibition, addressing the household of the Prophet. It calls the believers to repentance and warns of the fire fueled by people and stones."},
  {67, "Al-Mulk", "سُورَةُ المُلۡكِ", "The Sovereignty", "Meccan", 30, "The sovereignty, affirming that the kingdom is in the hand of Allah. It describes the perfection of the creation of the heavens and warns of the punishment of the fire."},
  {68, "Al-Qalam", "سُورَةُ القَلَمِ", "The Pen", "Meccan", 52, "The pen, by which the angels write the deeds. It defends the character of the Prophet against accusations of madness."},
  {69, "Al-Haaqqa", "سُورَةُ الحَاقَّةِ", "The Reality", "Meccan", 52, "The reality, the Day of Judgment that is certain to come. It describes the destruction of previous nations and the terror of that Day."},
  {70, "Al-Ma'aarij", "سُورَةُ المَعَارِجِ", "The Ascending Stairways", "Meccan", 44, "The ascending stairways, referring to the ways of ascent in the heavens. It describes the nature of man in haste and the stages of the Day of Judgment."},
  {71, "Nooh", "سُورَةُ نُوحٍ", "Noah", "Meccan", 28, "Named after Prophet Nuh, who called his people for nine hundred fifty years. It recounts his patience and the flood that destroyed the disbelievers."},
  {72, "Al-Jinn", "سُورَةُ الجِنِّ", "The Jinn", "Meccan", 28, "The jinn, a group of whom heard the Quran and believed. It affirms that Allah has no partner or offspring and that His knowledge encompasses the unseen."},
  {73, "Al-Muzzammil", "سُورَةُ المُزَّمِّلِ", "The Enshrouded One", "Meccan", 20, "The enshrouded one, an early address to the Prophet wrapped in his garment. It commands the night prayer and the recitation of the Quran in slow measured tones."},
  {74, "Al-Muddaththir", "سُورَةُ المُدَّثِّرِ", "The Cloaked One", "Meccan", 56, "The cloaked one, calling the Prophet to arise and warn. It describes the one who hoards wealth and the keepers of Hell."},
  {75, "Al-Qiyaama", "سُورَةُ القِيَامَةِ", "The Resurrection", "Meccan", 40, "The resurrection, sworn by the self-reproaching soul. It warns the denier of the gathering of the bones and of the day when faces will be bright and dark."},
  {76, "Al-Insaan", "سُورَةُ الإِنسَانِ", "Man", "Medinan", 31, "The man, describing the creation of humanity from a drop of mixed fluid. It paints the reward of the righteous with cups, springs, and eternal gardens."},
  {77, "Al-Mursalaat", "سُورَةُ المُرۡسَلَاتِ", "The Emissaries", "Meccan", 50, "The emissaries, the winds sent forth one after another. It repeats the warning of woe to the deniers of the Day of Decision."},
  {78, "An-Naba", "سُورَةُ النَّبَإِ", "The Announcement", "Meccan", 40, "The tidings, the great news of the resurrection. It lists the signs of Allah in creation and the punishments of the rebellious."},
  {79, "An-Naazi'aat", "سُورَةُ النَّازِعَاتِ", "Those who drag forth", "Meccan", 46, "Those who drag forth, the angels who pull out the souls. It contrasts the fate of the defiant with the gardens of the righteous."},
  {80, "Abasa", "سُورَةُ عَبَسَ", "He frowned", "Meccan", 42, "He frowned, rebuking the Prophet for turning away from the blind man. It teaches that the remembrance of Allah is for everyone who seeks it."},
  {81, "At-Takwir", "سُورَةُ التَّكۡوِيرِ", "The Overthrowing", "Meccan", 29, "The overthrowing, when the sun is folded up. It lists the portents of the Hour and honors the angel Jibreel who brought the revelation."},
  {82, "Al-Infitaar", "سُورَةُ الانفِطَارِ", "The Cleaving", "Meccan", 19, "The cleaving, when the sky is split apart. It reminds that the deeds of every soul are recorded by noble guardian angels."},
  {83, "Al-Mutaffifin", "سُورَةُ المُطَفِّفِينَ", "Defrauding", "Meccan", 36, "The defrauders, who cheat in measure and weight. It warns of the book of the wicked and the sealed wine of the righteous."},
  {84, "Al-Inshiqaaq", "سُورَةُ الانشِقَاقِ", "The Splitting Open", "Meccan", 25, "The splitting open, when the earth is spread out and gives up what is within. It separates the one given his record in his right hand from the one given it behind his back."},
  {85, "Al-Burooj", "سُورَةُ البُرُوجِ", "The Constellations", "Meccan", 22, "The constellations of the sky, sworn by the starry heavens. It tells of the people of the ditch who were burned for their faith."},
  {86, "At-Taariq", "سُورَةُ الطَّارِقِ", "The Morning Star", "Meccan", 17, "The nightcomer, the star that pierces the darkness. It calls on man to reflect on what he is created from."},
  {87, "Al-A'laa", "سُورَةُ الأَعۡلَىٰ", "The Most High", "Meccan", 19, "The Most High, glorifying the name of the Lord. It reassures the Prophet that he will be enabled to recite and remember."},
  {88, "Al-Ghaashiya", "سُورَةُ الغَاشِيَةِ", "The Overwhelming", "Meccan", 26, "The overwhelming, the Day that covers all faces. It contrasts the faces of the humbled with the faces of those joyful in gardens."},
  {89, "Al-Fajr", "سُورَةُ الفَجۡرِ", "The Dawn", "Meccan", 30, "The dawn, sworn with the ten nights and the even and the odd. It recalls the fate of Aad, Thamud, and Pharaoh and the regret of the one who says if only I had sent ahead."},
  {90, "Al-Balad", "سُورَةُ البَلَدِ", "The City", "Meccan", 20, "The city, meaning Makkah where the Prophet was born. It reminds that man was created for toil and points to the two paths of good and evil."},
  {91, "Ash-Shams", "سُورَةُ الشَّمۡسِ", "The Sun", "Meccan", 15, "The sun and its brightness, one of the great oaths of the Quran. It sets before man the choice to purify or corrupt his soul."},
  {92, "Al-Lail", "سُورَةُ اللَّيۡلِ", "The Night", "Meccan", 21, "The night when it covers, contrasted with the day when it brightens. It distinguishes the one who gives and fears from the one who hoards."},
  {93, "Ad-Dhuhaa", "سُورَةُ الضُّحَىٰ", "The Morning Hours", "Meccan", 11, "The morning hours, an early comfort to the Prophet. It assures him that his Lord has not forsaken him and that the later will be better than the earlier."},
  {94, "Ash-Sharh", "سُورَةُ الشَّرۡحِ", "The Consolation", "Meccan", 8, "The relief, expanding the chest of the Prophet and lifting his burden. It promises that with hardship comes ease."},
  {95, "At-Tin", "سُورَةُ التِّينِ", "The Fig", "Meccan", 8, "The fig and the olive, sacred lands where prophets were sent. It declares that man was created in the best of forms but can be brought to the lowest."},
  {96, "Al-Alaq", "سُورَةُ العَلَقِ", "The Clot", "Meccan", 19, "The clot, the first revealed verses commanding to read in the name of the Lord. It rebukes the one who prevents the servant from praying."},
  {97, "Al-Qadr", "سُورَةُ القَدۡرِ", "The Power, Fate", "Meccan", 5, "The night of power, better than a thousand months. It describes the descent of the angels and the peace of that night until dawn."},
  {98, "Al-Bayyina", "سُورَةُ البَيِّنَةِ", "The Evidence", "Medinan", 8, "The clear proof, the messenger reciting purified scrolls. It separates the people of the book and the polytheists into the best of creation and the worst."},
  {99, "Az-Zalzala", "سُورَةُ الزَّلۡزَلَةِ", "The Earthquake", "Medinan", 8, "The earthquake of the Day of Judgment. It declares that whoever does an atom of good or evil will see it."},
  {100, "Al-Aadiyaat", "سُورَةُ العَادِيَاتِ", "The Chargers", "Meccan", 11, "The chargers that run and breathe fire, sworn by the war horses. It exposes the ingratitude and greed of man toward his Lord."},
  {101, "Al-Qaari'a", "سُورَةُ القَارِعَةِ", "The Calamity", "Meccan", 11, "The calamity that strikes, the Day of Judgment. It weighs the deeds and settles the scales, granting a pleasant life to the heavy and a deep pit to the light."},
  {102, "At-Takaathur", "سُورَةُ التَّكَاثُرِ", "Competition", "Meccan", 8, "The rivalry in the increase of wealth and numbers. It warns that the craving distracts until one visits the graves."},
  {103, "Al-Asr", "سُورَةُ العَصۡرِ", "The Declining Day, Epoch", "Meccan", 3, "The declining day, sworn by time itself. It declares that mankind is in loss except those who believe, do good, and counsel each other in truth and patience."},
  {104, "Al-Humaza", "سُورَةُ الهُمَزَةِ", "The Traducer", "Meccan", 9, "The traducer who mocks and sneers. It warns of the crushing fire that reaches to the hearts."},
  {105, "Al-Fil", "سُورَةُ الفِيلِ", "The Elephant", "Meccan", 5, "The elephant, recalling the army that marched to destroy the Kaaba. Allah sent birds with stones of clay and made their plan come to nothing."},
  {106, "Quraish", "سُورَةُ قُرَيۡشٍ", "Quraysh", "Meccan", 4, "Named after the tribe of the Prophet, custodians of the sacred house. It calls them to worship the Lord of this house who fed them against hunger and secured them from fear."},
  {107, "Al-Maa'un", "سُورَةُ المَاعُونِ", "Almsgiving", "Meccan", 7, "The small kindnesses, rebuking those who deny the Day of Judgment. It describes those who pray carelessly and refuse the smallest help to the needy."},
  {108, "Al-Kawthar", "سُورَةُ الكَوۡثَرِ", "Abundance", "Meccan", 3, "The abundance, a river granted to the Prophet in Paradise. It tells him to pray and sacrifice for his Lord, for his enemy is the one cut off."},
  {109, "Al-Kaafiroon", "سُورَةُ الكَافِرُونَ", "The Disbelievers", "Meccan", 6, "The disbelievers, commanding a clear separation of worship. You have your religion and I have mine."},
  {110, "An-Nasr", "سُورَةُ النَّصۡرِ", "Divine Support", "Medinan", 3, "The divine support and the conquest, revealed when Makkah was opened. It commands praise and seeking of forgiveness as the people enter the religion in crowds."},
  {111, "Al-Masad", "سُورَةُ المَسَدِ", "The Palm Fibre", "Meccan", 5, "The palm fibre, condemning Abu Lahab and his wife. Their wealth and deeds will not avail them against the fire."},
  {112, "Al-Ikhlaas", "سُورَةُ الإِخۡلَاصِ", "Sincerity", "Meccan", 4, "The sincerity, declaring Allah as the One, the Eternal Refuge. It is regarded as equal to a third of the Quran."},
  {113, "Al-Falaq", "سُورَةُ الفَلَقِ", "The Dawn", "Meccan", 5, "The daybreak, seeking refuge in the Lord of the dawn. It protects from the evil of the created things, the darkness, and the envious."},
  {114, "An-Naas", "سُورَةُ النَّاسِ", "Mankind", "Meccan", 6, "Mankind, seeking refuge in the Lord of people, the King of people, and the God of people. It is a protection from the whisperer who withdraws."},
};

void getSurahMeta(int surahNum, Surah *out) {
    if (surahNum < 1 || surahNum > TOTAL_SURAHS) return;
    *out = SURAH_META[surahNum - 1];
}

